### ISSUE TITLE
Support for OS X 10.8 Mountain Lion

### ISSUE THREAD

**Issue by scdwyer** [paparazzi/paparazzi-portability-support#38]
A number of requests have made to provide mountain lion support.

@rbdavison You mentioned you might be starting on this soon?

@esden You have already tried installing on Mountain Lion? Any further comments or progress on this? You wrote an email on the list here: http://lists.gnu.org/archive/html/paparazzi-devel/2012-09/msg00053.html

Also brings up the issue, how many OS X versions should be supported? As there are only a few people actually testing/developing for it, it is hard to have too many versions.

**Comment by flixr** [comment]
long fixed...
