### ISSUE TITLE
Debian stretch installation problem

### ISSUE THREAD

**Issue by garciafa** [paparazzi/paparazzi-portability-support#44]
Hello,

I have a problem installing paparazzi in a Debian stable (a.k.a. stretch/9).
I tried installing the package paparazzi-dev from the Debian_8.0 repository but there were two problems: 
- The first minor is that the key of the repository cannot be trusted by apt. The signature A20590F9DFDAD3DA441698C44F102E9639B84059 is said to be invalid (though I could not determine why)

- The second is due to package ivy-ocaml that depends on ocaml-base-nox-4.01.0. The new version of ocaml-base-nox is 4.02.3-9. Is it possible to make ivy-ocaml depend on ocaml-base-nox >= 4.01.0 so as to have upward compatibility ?

Thanks a lot,
Fabien Garcia

**Comment by flixr** [comment]
We don't have packages for stretch yet...
I'll try to add stretch ASAP

**Comment by flixr** [comment]
Packages for stretch should be ready as soon as they are picked up by the scheduler.
See https://build.opensuse.org/project/monitor/home:flixr:paparazzi-uav?arch_x86_64=1&blocked=1&broken=1&building=1&defaults=0&deleting=1&dispatching=1&failed=1&finished=1&locked=1&repo_Debian_9_0=1&scheduled=1&signing=1&succeeded=1&unresolvable=1

I also updated the wiki: https://wiki.paparazziuav.org/wiki/Installation/Linux#Debian

Please remove the jessie repo and add the stretch repo and let me know if there are further problems...

**Comment by garciafa** [comment]
Le 24/08/2017 à 20:52, Felix Ruess a écrit :
>
> Packages for stretch should be ready as soon as they are picked up by
> the scheduler.
> See
> https://build.opensuse.org/project/monitor/home:flixr:paparazzi-uav?arch_x86_64=1&blocked=1&broken=1&building=1&defaults=0&deleting=1&dispatching=1&failed=1&finished=1&locked=1&repo_Debian_9_0=1&scheduled=1&signing=1&succeeded=1&unresolvable=1
>
> I also updated the wiki:
> https://wiki.paparazziuav.org/wiki/Installation/Linux#Debian
>
> Please remove the jessie repo and add the stretch repo and let me know
> if there are further problems...
>
Hello Felix,

I just tested the stretch repo and everything went smoothly, install and
compilation of paparazzi.

Thanks a lot for your fast help !

Fabien
